backend:
  name: github
  repo: atelierbram/hugo-netlify-test # Path to your Github repository
  branch: master # Branch to update
  publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


# https://github.com/netlify/netlify-cms/blob/master/example/config.yml
collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "blog"
    slug: "{{slug}}"

  - name: "Page" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Page" # Used in the UI, ie.: "New Post"
    folder: "/"
    slug: "{{slug}}"
