backend:
  name: github
  repo: atelierbram/hugo-netlify-test # Path to your Github repository
  branch: master # Branch to update
  publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


# https://github.com/netlify/netlify-cms/blob/master/example/config.yml
collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/post"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title"}
      - {label: "Publish Date", name: "date", format: "YYYY-MM-DD hh:mma"}

  - name: "page" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Page" # Used in the UI, ie.: "New Post"
    folder: "content"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title"}
      - {label: "Publish Date", name: "date", format: "YYYY-MM-DD hh:mma"} 
